services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: egzona
      POSTGRES_PASSWORD: egzona
      POSTGRES_DB: egzona_abazi
    ports:
      - "5433:5432"
    volumes:
      - egzona_db_data:/var/lib/postgresql/data

volumes:
  egzona_db_data:
